# Generated by ChatGPT on 2026-04-01

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_catalog(apps, schema_editor):
    YarnBrand = apps.get_model('constructor', 'YarnBrand')
    YarnColor = apps.get_model('constructor', 'YarnColor')
    HatModel = apps.get_model('constructor', 'HatModel')
    HatKnitStyle = apps.get_model('constructor', 'HatKnitStyle')
    StoneCatalogItem = apps.get_model('constructor', 'StoneCatalogItem')
    ClaspType = apps.get_model('constructor', 'ClaspType')

    brands = {
        'wool-air': YarnBrand.objects.create(
            name='Wool & Air',
            slug='wool-air',
            description='Базовая демонстрационная фирма пряжи. Реальные данные можно заменить через админку.',
            sort_order=10,
            is_active=True,
        ),
        'merino-studio': YarnBrand.objects.create(
            name='Merino Studio',
            slug='merino-studio',
            description='Вторая демонстрационная фирма для проверки фильтрации по бренду.',
            sort_order=20,
            is_active=True,
        ),
    }

    color_rows = [
        ('wool-air', 'Графит', 'graphite', '#5B5F66', 10),
        ('wool-air', 'Молочный', 'milk', '#F1EEE7', 20),
        ('wool-air', 'Какао', 'cocoa', '#8A6B55', 30),
        ('wool-air', 'Ягодный', 'berry', '#7A1F34', 40),
        ('merino-studio', 'Серебристый туман', 'silver-mist', '#B8BBC3', 10),
        ('merino-studio', 'Песочный', 'sand', '#CDBA9A', 20),
        ('merino-studio', 'Хвойный', 'pine', '#65735C', 30),
        ('merino-studio', 'Ночной синий', 'midnight-blue', '#334A68', 40),
    ]
    for brand_slug, name, slug, hex_value, sort_order in color_rows:
        YarnColor.objects.create(
            brand=brands[brand_slug],
            name=name,
            slug=slug,
            hex_value=hex_value,
            sort_order=sort_order,
            is_active=True,
        )

    knit_rows = [
        ('fine', 'Мелкая вязка', 'Плотная и аккуратная, заметно крупнее, чем в текущей версии.', 24, Decimal('1.00'), 10),
        ('chunky', 'Крупная вязка', 'Объёмная фактура с более выраженным шагом петли.', 12, Decimal('1.45'), 20),
    ]
    for code, name, description, texture_density, texture_scale, sort_order in knit_rows:
        HatKnitStyle.objects.create(
            code=code,
            name=name,
            description=description,
            texture_density=texture_density,
            texture_scale=texture_scale,
            sort_order=sort_order,
            is_active=True,
        )

    hat_rows = [
        ('Бини', 'beanie', 'img/catalog/hats/beanie.svg', 'Универсальная базовая посадка.', 10),
        ('Капор-шарф', 'hood-scarf', 'img/catalog/hats/hood-scarf.svg', 'Мягкий объёмный капор с длинными концами.', 20),
        ('Балаклава', 'balaclava', 'img/catalog/hats/balaclava.svg', 'Закрытая форма для плотной посадки.', 30),
        ('Капор с ушками', 'cat-hood', 'img/catalog/hats/cat-hood.svg', 'Акцентная модель с декоративными ушками.', 40),
        ('Бини с помпоном', 'pompom-beanie', 'img/catalog/hats/pompom-beanie.svg', 'Зимняя классика с помпоном.', 50),
        ('Ушанка', 'ushanka', 'img/catalog/hats/ushanka.svg', 'Модель с боковыми ушками.', 60),
    ]
    for name, slug, asset_path, description, sort_order in hat_rows:
        HatModel.objects.create(
            name=name,
            slug=slug,
            preview_asset_path=asset_path,
            description=description,
            render_preset={},
            sort_order=sort_order,
            is_active=True,
        )

    stone_rows = [
        ('Розовый кварц', 'rose-quartz', 'img/catalog/stones/rose-quartz.svg', '#E6C7D0', 'Кварц', Decimal('6.0'), None, 10),
        ('Оникс', 'onyx', 'img/catalog/stones/onyx.svg', '#2C2D31', 'Минерал', Decimal('6.0'), None, 20),
        ('Авантюрин', 'aventurine', 'img/catalog/stones/aventurine.svg', '#7CA17C', 'Минерал', Decimal('8.0'), None, 30),
        ('Жемчуг', 'pearl', 'img/catalog/stones/pearl.svg', '#F2EEE8', 'Перламутр', Decimal('10.0'), Decimal('11.0'), 40),
        ('Янтарь', 'amber', 'img/catalog/stones/amber.svg', '#C98531', 'Смола', Decimal('8.0'), None, 50),
        ('Лабрадорит', 'labradorite', 'img/catalog/stones/labradorite.svg', '#5A6475', 'Минерал', Decimal('10.0'), Decimal('10.5'), 60),
        ('Горный хрусталь', 'crystal', 'img/catalog/stones/crystal.svg', '#D8E7F0', 'Кристалл', Decimal('6.0'), None, 70),
        ('Гематит', 'hematite', 'img/catalog/stones/hematite.svg', '#6D6D73', 'Минерал', Decimal('8.0'), None, 80),
    ]
    for name, slug, asset_path, color_hex, material, diameter_mm, visual_length_mm, sort_order in stone_rows:
        StoneCatalogItem.objects.create(
            name=name,
            slug=slug,
            preview_asset_path=asset_path,
            color_hex=color_hex,
            material=material,
            diameter_mm=diameter_mm,
            visual_length_mm=visual_length_mm,
            sort_order=sort_order,
            is_active=True,
        )

    clasp_rows = [
        ('Карабин', 'lobster', 'img/catalog/clasps/lobster.svg', Decimal('14.0'), 'Металл', 10),
        ('Тогл', 'toggle', 'img/catalog/clasps/toggle.svg', Decimal('18.0'), 'Металл', 20),
        ('Магнитная', 'magnetic', 'img/catalog/clasps/magnetic.svg', Decimal('16.0'), 'Металл', 30),
        ('Крючок', 'hook', 'img/catalog/clasps/hook.svg', Decimal('13.0'), 'Металл', 40),
    ]
    for name, slug, asset_path, visual_length_mm, material, sort_order in clasp_rows:
        ClaspType.objects.create(
            name=name,
            slug=slug,
            preview_asset_path=asset_path,
            visual_length_mm=visual_length_mm,
            material=material,
            sort_order=sort_order,
            is_active=True,
        )


def drop_catalog(apps, schema_editor):
    apps.get_model('constructor', 'YarnColor').objects.all().delete()
    apps.get_model('constructor', 'YarnBrand').objects.all().delete()
    apps.get_model('constructor', 'HatModel').objects.all().delete()
    apps.get_model('constructor', 'HatKnitStyle').objects.all().delete()
    apps.get_model('constructor', 'StoneCatalogItem').objects.all().delete()
    apps.get_model('constructor', 'ClaspType').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_extragenerationpurchase_receipts_and_admin_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaspType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('preview_asset_path', models.CharField(blank=True, help_text='Путь к статическому превью застёжки внутри static.', max_length=255)),
                ('visual_length_mm', models.DecimalField(decimal_places=1, default=Decimal('14.0'), max_digits=6)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Застёжка',
                'verbose_name_plural': 'Застёжки',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HatKnitStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('texture_density', models.PositiveIntegerField(default=18)),
                ('texture_scale', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
            ],
            options={
                'verbose_name': 'Тип вязки',
                'verbose_name_plural': 'Типы вязки',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('preview_asset_path', models.CharField(help_text='Путь к PNG/WebP/SVG на прозрачном фоне внутри static.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('render_preset', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Модель шапки',
                'verbose_name_plural': 'Модели шапок',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StoneCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('preview_asset_path', models.CharField(blank=True, help_text='Путь к статическому превью камня внутри static.', max_length=255)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('diameter_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('visual_length_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Если элемент визуально занимает больше места, чем диаметр, задайте это значение.', max_digits=6, null=True)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('shape', models.CharField(default='round', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Камушек',
                'verbose_name_plural': 'Камушки',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='YarnBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Фирма пряжи',
                'verbose_name_plural': 'Фирмы пряжи',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MasterInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hat', 'Шапка'), ('jewelry', 'Украшение')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('selections', models.JSONField(blank=True, default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='master_inquiries/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка мастеру',
                'verbose_name_plural': 'Заявки мастеру',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='YarnColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=140)),
                ('hex_value', models.CharField(help_text='HEX-цвет вида #AABBCC', max_length=7)),
                ('swatch_asset_path', models.CharField(blank=True, help_text='Путь к статическому изображению палитры, например img/catalog/swatches/graphite.png', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='constructor.yarnbrand')),
            ],
            options={
                'verbose_name': 'Цвет пряжи',
                'verbose_name_plural': 'Цвета пряжи',
                'ordering': ('brand__sort_order', 'sort_order', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='yarncolor',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='uniq_yarn_color_per_brand'),
        ),
        migrations.RunPython(seed_catalog, reverse_code=drop_catalog),
    ]
